artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data ingestion
  source_URL: https://drive.google.com/file/d/1ed9LYT5H4zrFWp4tzAU-zOkpdOX-BEF8/view?usp=sharing
  local_data_file: artifacts/data ingestion/data.zip
  unzip_dir: artifacts/data ingestion




prepare_base_model:
  root_dir: artifacts/prepare base model
  base_model_path: artifacts/prepare base model/base_model.h5
  updated_base_model_path: artifacts/prepare base model/base_model_updated.h5


training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5
  